### ISSUE TITLE
Prepare a contribution guidelines doc

### ISSUE THREAD

**Issue by almo** [ml4rookies/Course#13]
Review a few examples, before to produce our own contribution guidelines. In particular
  - Go Contributing Guidelines [1]
  - TensorFlow Contributing Guidelines [2]

[1] https://go.googlesource.com/pkgsite/+/refs/heads/master/CONTRIBUTING.md
[2] https://www.tensorflow.org/community/contribute/code

**Comment by SamuelMarks** [comment]
We might want a commit naming guideline and some linting hooks, if not the full CI/CD before merging.

**Comment by almo** [comment]
Obsolete.
