### ISSUE TITLE
Wrong order of images at 00.Introduction

### ISSUE THREAD

**Issue by mrutid** [ml4rookies/Course#28]
Images at are in the wrong order:
https://github.com/ml4rookies/Course/blob/master/00.Introduction/README.md

![image](https://user-images.githubusercontent.com/968372/92362380-375ed300-f0f0-11ea-8cce-956f080ea1b2.png)

**Comment by Aqsa-K** [comment]
Thanks for pointing out. I'll correct it :+1:
