### ISSUE TITLE
Rebranding Organization to ml4rookies.github.io

### ISSUE THREAD

**Issue by almo** [ml4rookies/Course#5]

**Comment by aabedraba** [comment]
I suggest the new website to be written using https://www.docz.site/

It allows for use of MDX (Markdown with JS, but the second is optional) and builds a static website for it. 

Example of use can be found here: https://guidesmiths.github.io/cybersecurity-handbook/

If it looks good, I can start implementing it!

**Comment by bazarum** [comment]
For me it looks ok!!!
What are he next steps? How we could help you?

**Comment by almo** [comment]
Thank you for joining us!
Really appreciate your contributions.
I will invite you to our organization.

Couple of comments here:
- For me is ok to use docx/mdx: you do, you choose. It is the power of doing!
- Keep this in a separate branch. We can pull the master when ready.
- In our project, master source of the doc is a separated repository. This allows us separate visualisation from the content production, but it also makes a little bit harder to merge copy with landing. This is not a final decision, so happy to explore other options.  

Welcome!

**Comment by sayakpaul** [comment]
@almo including https://fastpages.fast.ai/ as an alternate to convert the markdowns to blog posts like this: https://sayak.dev/tf.keras/data_augmentation/image/2020/05/10/augmemtation-recipes.html

**Comment by aabedraba** [comment]
Hey @sayakpaul this is a great one!! 

What I like is that you don't only use markdown, but Jupyter notebooks which are connected to Collab. Perfect for our use-case.

Perhaps it doesn't include a content-like visualization that you'd expect from an educational "book". It's my impression. Check the first draft using `docz` that I implemented yesterday [here](https://ml4rookies.now.sh/). WDYT?

Also, probably we should take this conversation to the website repo.

**Comment by sayakpaul** [comment]
Those are probably supported and you can check them here: https://fastpages.fast.ai/. An entire education book was actually written using it: https://github.com/fastai/fastbook :)

**Comment by almo** [comment]
Dear fellows, 
Today I have rebranded our organization. 
Unfortunately, [mlstarter](https://github.com/MLStarter) was taken, so I went for ML4Rookies.
We can still use ML Starter in the documentation.
Please update your local repositories.
Best
